import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "Hello from slint";

    width: 720px;
    height: 1280px;
    
    VerticalBox {
        Text {
            text: "Hello from slint!";
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.center;
            
            font-size: 18px + 16px * abs(sin(360deg * animation-tick() / 3s));
        }
    }
}
